name: Test Env Secrets
on:
  push:
    branches:
      - "dev-test-workflow"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - run: echo "Firebase api key ${{ env.FIREBASE_API_KEY }}"
      - run: echo "Base URL ${{ env.BASE_URL }}"
      - run: echo "Base URL ${{ env.TEST_KEY }}"
